language: r
sudo: false
cache: false

r:
  - oldrel
  - release

os:
  - osx

script:
  - Rscript -e "rmarkdown::render('examples/lecture-08b.Rmd')"
  - Rscript -e "rmarkdown::render('examples/lecture-08c.Rmd')"
  - Rscript -e "rmarkdown::render('assignments/lab-07/lab-07-replication/docs/lab-07.Rmd')"