# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

before_test:
  - ps: >-
      if (-Not (Test-Path "C:\Program Files (x86)\Pandoc\")) {
        cinst pandoc
      }
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"
  - pandoc -v
  - Rscript -e "tidycensus::census_api_key(key = '53fc755a8599dfb7e6596b320e7eac0b3f36105d', install = TRUE)"

environment:
  global:
    WARNINGS_ARE_ERRORS: 1

  matrix:
    - R_VERSION: patched
      R_ARCH: x64

    - R_VERSION: patched

    - R_VERSION: release
      R_ARCH: x64

    - R_VERSION: release

    - R_VERSION: oldrel
      R_ARCH: x64

    - R_VERSION: oldrel

matrix:
  fast_finish: true

build_script:
  - travis-tool.sh install_deps

test_script:
  - Rscript -e "rmarkdown::render('examples/lecture-08b.Rmd')"
  - Rscript -e "rmarkdown::render('examples/lecture-08c.Rmd')"
  - Rscript -e "rmarkdown::render('assignments/lab-07/lab-07-replication/docs/lab-07.Rmd')"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits